name: CI Pipeline

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build-and-test:
    defaults:
      run:
        working-directory: ./idz
    runs-on: ubuntu-latest

    steps:
      - name: Отримання коду
        uses: actions/checkout@v4

      - name: Встановлення Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Встановлення залежностей
        run: make setup

      - name: Перевірка форматування (Black)
        run: make format-check

      - name: Запуск тестів (Unittest & Doctest)
        run: make test
